before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - RELEASE_VERSION="{{ .Tag }}"
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X "main.Version={{ .Tag }}"
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
